import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';
import Link from 'next/link';

export default function Home() {

  const [data, setData] = useState([]);
  
  useEffect(() => {
    fetch('/api/aws')
      .then(response => response.json())
      .then(data => setData(data))
      .catch(error => console.error(error));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://aws.amazon.com/">AWS!</a>
        </h1>

        <p className={styles.description}>This is just a test project.</p>
        <p className={styles.description}>Data from database:</p>

        <table className={styles.table}>
          <thead>
            <tr>
              <th className={styles.th}>Name</th>
              <th className={styles.th}>Email</th>
              <th className={styles.th}>Username</th>
            </tr>
          </thead>
          <tbody>
            {data ? console.log(data) : ''}
            {
              data.length > 0 ? data.map(item => (
                <tr key={item.id} className={styles.tr}>
                  <td className={styles.td}>{item.name}</td>
                  <td className={styles.td}>{item.email}</td>
                  <td className={styles.td}>{item.username}</td>
                </tr>
              )) : 'Loading...'
            }
          </tbody>
        </table>

      </main>

      <footer className={styles.footer}>
          A test project by{' '} <Link href="https://jamestrent.net">James Trent</Link>.
      </footer>
    </div>
  )
}
